routes/web.php
<?php

Auth::routes();

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/editor', 'WelcomeController@editor');
Route::get('/home', 'WelcomeController@home');


Route::get('/init', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth','admin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('categories', 'CategoryController@index');
    Route::get('categories/create', 'CategoryController@create');
   
    Route::post('categories/create', 'CategoryController@store');
    Route::get('categories/{id}/edit', 'CategoryController@edit');
    
    Route::post('categories/{id}/edit', 'CategoryController@update');
    Route::get('categories/{id}/delete', 'CategoryController@delete');

    Route::get('pictures', 'PictureController@index');
    Route::get('pictures/create', 'PictureController@create');
    Route::post('pictures/create', 'PictureController@store');
    Route::get('pictures/{id}/edit', 'PictureController@edit');
    Route::post('pictures/{id}/edit', 'PictureController@update');
    Route::get('pictures/{picture}/guide', 'PictureController@getGuide');
    Route::post('pictures/{picture}/guide', 'PictureController@postGuide');
    Route::get('pictures/{picture}/images', 'PictureImageController@index');
    Route::post('pictures/ornament', 'PictureImageController@upload');
    Route::post('pictures/{picture}/images', 'PictureImageController@store');
    Route::get('pictures/{id}/delete', 'PictureController@delete');

    //Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    //Route::post('register', 'Auth\RegisterController@register');
});

Route::group(['middleware' => ['auth','teacher'], 'namespace' => 'Teacher', 'prefix' => 'teacher'], function () {
    Route::get('students', 'StudentController@index');
    Route::get('students/create', 'StudentController@create');
    Route::post('students/create', 'StudentController@store');
    Route::get('students/{id}/edit', 'StudentController@edit');
    Route::post('students/{id}/edit', 'StudentController@update');
    Route::get('students/{id}/delete', 'StudentController@delete');
    Route::get('students/{id}/reports', 'StudentController@reports');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('category/{id}/pictures', 'CategoryController@index');
    Route::get('category/{category_id}/pictures/{picture_id}', 'ExerciseController@index');

    Route::get('pictures/{picture}/play', 'ExerciseController@play');
    Route::post('pictures/{pictureId}/play', 'ExerciseController@store');
    Route::get('/next', 'ExerciseController@next');
});

app/Picture.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Picture extends Model
{
    use SoftDeletes;

    public function getImageUrlAttribute(){

        return '/images/pictures/'.$this->image;
    }

    public function getVideoUrlAttribute(){

        return '/videos/'.$this->video;
    }
}

resources/views/exercise.blade.php
@extends('layouts.app')

@section('content')
    <div class="example">
        <div class="row" id="game-content">
            <div class="col-xl-12 col-sm-12">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item">
                                        <a class="breadcrumb-link" href="/">Inicio</a>
                                    </li>
                                    <li class="breadcrumb-item">
                                        <a class="breadcrumb-link" href="{{ url('category/'.$category->id.'/pictures') }}">{{ $category->name }}</a>
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">{{ $picture->name }}</li>
                                </ol>
                            </nav>
                        </div>
                        <div class="col-12 text-center">
                            <iframe width="560" height="315" src="{{ $picture->video_url }}" frameborder="0" allowfullscreen>
                            </iframe>

                            @if ($picture->description)
                                <p>{{ $picture->description }}</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-12">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12" id="icon-bar">
                            <div class="row">
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-3"> </div>
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-6" id="btn-row">
                                    <div class="row">
                                        <div class="col-6 game-icons" id="inicio">
                                            <a href="/">
                                                <img class="icon-img" src="{{ asset('images/inicio.png') }}" alt="Botón para volver al inicio">
                                            </a>
                                            <p class="icon-text">Inicio</p>
                                        </div>
                                        <div class=" col-6 game-icons" id="inicio">
                                            <a href="{{ url('/pictures/'.$picture->id.'/play') }}">
                                                <img class="icon-img" src="{{ asset('images/play.png') }}" alt="Botón para iniciar el juego" title="Clic para iniciar">
                                            </a>
                                            <p class="icon-text">Empezar</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>tefa

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pictures.blade.php
@extends('layouts.app')

@section('content')
    <div class="example">
        <div id="lenguaje">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 panel-title-container">
                        <img class="level-thumb-img" src="{{ $category->image_url }}" alt="{{ $category->name }}">
                    </div>
                </div>
            </div>
        </div>
        <div id="lenguaje-thumb-div" class="thumbnail-container collapse show">
            <div class="container">
                <div class="row level-thumb-row">
                    <div class="col-xl-12 col-12">
                        <div class="row">
                            @foreach($category->pictures as $picture)
                                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 col-6">
                                    <div class="card thumbnail-card">
                                        <a class="thumbnail-item-link" href="{{ url('category/'.$category->id.'/pictures/'.$picture->id) }}" style="text-decoration: none;">
                                            <img class="img-fluid thumb-img" src="{{ $picture->image_url }}" alt="{{ $picture->name }}">
                                            <div class="card-body thumbnail-card-body lenguaje-card">
                                                <p class="thumbnail-name">{{ $picture->name }}</p>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            @endforeach
                        </div>

                        <div class="row mt-5">
                            <div class="col-12 text-center game-icons" id="inicio">
                                <a href="/">
                                    <img class="icon-img" src="{{ asset('images/inicio.png') }}"
                                         width="70" height="70"
                                         alt="Botón para volver al inicio">
                                </a>
                                <p class="icon-text">Inicio</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/welcomeNew.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <section class="bg-blue block-welcome roww">
            <div class="col-md-12">
                <div class="row block-top">
                    <div class="col figure-welcome size-2">
                        <img class="animated bounceInDown delay-1s" src="/images/bienvenida/letra (3).png" alt="">
                    </div>
                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-1s" src="/images/bienvenida/colores (5).png" alt="">
                    </div>
                    <div class="col figure-welcome size-1" >
                        <img class="animated bounceInDown delay-3s" src="/images/bienvenida/colores (1).png" alt="">
                    </div>
                    <div class="col figure-welcome size-1">
                        <img  class="animated bounceInDown delay-5s"src="/images/bienvenida/crayola (1).png" alt="">
                    </div>
                    <div class="col figure-welcome size-1">
                        <img  class="animated bounceInDown delay-2s"src="/images/bienvenida/crayola (2).png" alt="">
                    </div>
                    <div class="col figure-welcome size-2">
                        <img  class="animated bounceInDown delay-4s"src="/images/bienvenida/regla.png" alt="" >
                    </div>

                    <div class="col figure-welcome size-1">
                        <img  class="animated bounceInDown delay-3s"src="/images/bienvenida/num (1).png" alt="" >
                    </div>

                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-1s" src="/images/bienvenida/colores (4).png" alt="">
                    </div>
                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-3s" src="/images/bienvenida/colores (2).png" alt="">
                    </div>
                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-5s" src="/images/bienvenida/clic (2).png" alt="">
                    </div>
                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-2s" src="/images/bienvenida/tijera.png" alt="">
                    </div>
                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-4s" src="/images/bienvenida/colores (3).png" alt="">
                    </div>

                    <div class="col figure-welcome size-1">
                        <img  class="animated bounceInDown delay-3s"src="/images/bienvenida/num (3).png" alt="" >
                    </div>

                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-1s" src="/images/bienvenida/crayola (1).png" alt="">
                    </div>
                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-3s" src="/images/bienvenida/lupa.png" alt="">
                    </div>
                    
                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-1.5s" src="/images/bienvenida/letra (1).png" alt="">
                    </div>

                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-1s" src="/images/bienvenida/clic (2).png" alt="">
                    </div>
                    <div class="col figure-welcome size-3">
                        <img class="animated bounceInDown delay-1s" src="/images/bienvenida/e.png" alt="">
                    </div>
                    <div class="col figure-welcome size-3">
                        <img class="animated bounceInDown delay-3s" src="/images/bienvenida/f.png" alt="">
                    </div>
                    <div class="col figure-welcome size-3">
                        <img class="animated bounceInDown delay-1s" src="/images/bienvenida/p.png" alt="">
                    </div>

                    <div class="col figure-welcome size-1">
                        <img class="animated bounceInDown delay-2s" src="/images/bienvenida/letra (2).png" alt="">
                    </div>
                </div>
            </div>

            <div class="col-md-12 block-img-welcome">
                <div class="container">
                    <div class="row align-items-center width-100">
                        <div class="col-md-8 text-white">
                            <h1 class="animated fadeInLeft title-welcome">Bienvenidos</h1><br>
                            <img src="/images/LOGO (1).png" alt="" style="width: 400px;" class="img-fluid animated fadeInLeft delay-1s">
                        </div>
                        <div class="col-md-4 text-center d-none d-md-block">
                            <img src="/images/bienvenida/mochi.png" alt="" class="animated bounceInDown delay-1s img-banner">
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
@section('scripts')
    <script>
        $("#main-header").hide();
        $(".footer").hide();
        setTimeout(() => {
            window.location.pathname='/home';
        }, 4000);
    </script>
@endsection