routes/web.php
<?php

Auth::routes();

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/editor', 'WelcomeController@editor');
Route::get('/home', 'WelcomeController@home');


Route::get('/init', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth','admin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::get('categories', 'CategoryController@index');
    Route::get('categories/create', 'CategoryController@create');
   
    Route::post('categories/create', 'CategoryController@store');
    Route::get('categories/{id}/edit', 'CategoryController@edit');
    
    Route::post('categories/{id}/edit', 'CategoryController@update');
    Route::get('categories/{id}/delete', 'CategoryController@delete');

    Route::get('pictures', 'PictureController@index');
    Route::get('pictures/create', 'PictureController@create');
    Route::post('pictures/create', 'PictureController@store');
    Route::get('pictures/{id}/edit', 'PictureController@edit');
    Route::post('pictures/{id}/edit', 'PictureController@update');
    Route::get('pictures/{picture}/guide', 'PictureController@getGuide');
    Route::post('pictures/{picture}/guide', 'PictureController@postGuide');
    Route::get('pictures/{picture}/images', 'PictureImageController@index');
    Route::post('pictures/ornament', 'PictureImageController@upload');
    Route::post('pictures/{picture}/images', 'PictureImageController@store');
    Route::get('pictures/{id}/delete', 'PictureController@delete');

    //Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    //Route::post('register', 'Auth\RegisterController@register');
});

Route::group(['middleware' => ['auth','teacher'], 'namespace' => 'Teacher', 'prefix' => 'teacher'], function () {
    Route::get('students', 'StudentController@index');
    Route::get('students/create', 'StudentController@create');
    Route::post('students/create', 'StudentController@store');
    Route::get('students/{id}/edit', 'StudentController@edit');
    Route::post('students/{id}/edit', 'StudentController@update');
    Route::get('students/{id}/delete', 'StudentController@delete');
    Route::get('students/{id}/reports', 'StudentController@reports');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('category/{id}/pictures', 'CategoryController@index');
    Route::get('category/{category_id}/pictures/{picture_id}', 'ExerciseController@index');

    Route::get('pictures/{picture}/play', 'ExerciseController@play');
    Route::post('pictures/{pictureId}/play', 'ExerciseController@store');
    Route::get('/next', 'ExerciseController@next');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'apellido', 'email', 'password', 'rol_id', 'section_id'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getIsAdminAttribute() {
        return $this->role == 0;
    }

    public function getIsTeacherAttribute() {
        return $this->role == 1;
    }

    public function matches()
    {
        return $this->hasMany(Match::class);
    }

    public function roles(){
        return $this->belongsTo(Rol::class);
    }

    public function sections(){
        return $this->hasOne(Section::class);
    }

}

resources/views/includes/footer.blade.php
<div class="footer" id="contactanos" >
    <div class="container">
        <div class="row">
            <div class="col-12 block-footer">  
                <p id="copyright-txt">Copyright © {{ date("Y") }} Fipdeby School - Todos los derechos reservados.</p>
            </div>
        </div>
    </div>
</div>

resources/views/includes/menu.blade.php
    <header class="display-none" id="main-header">
        <nav class="navbar navbar-expand-md navbar-dark py-0 nav-top justify-content-between" style="">
            <a class="navbar-brand py-3" href="/home">
                <img src="{{ asset('/images/LOGO (1).png') }}" alt="Logo" id="logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="header-lists">
                <div class="navbar-collapse flex-md-column header-lists-user" id="" >
                    <ul class="navbar-nav nav-row py-0 ml-auto" id="nav-bottom">
                        {{--<li class="nav-item2 py-0" data-toggle="collapse" data-target=".navbar-collapse.show">--}}
                            {{--<a class="nav-link active py-0" href="#">Canciones</a>--}}
                        {{--</li>--}}
                        {{--<li class="nav-item2 dropdown py-0">--}}
                            {{--<a class="nav-link active dropdown-toggle py-0" data-toggle="dropdown" href="#">--}}
                                {{--Cuentos<span class="sr-only">(current)</span>--}}
                            {{--</a>--}}
                            {{--<div class="dropdown-menu" data-toggle="collapse" data-target=".navbar-collapse.show">--}}
                                {{--<a class="dropdown-item" href="/cuentos-infantiles-cortos">Cuentos infantiles cortos </a>--}}
                                {{--<a class="dropdown-item" href="/cuentos-clasicos-infantiles">Cuentos clásicos </a>--}}
                                {{--<a class="dropdown-item" href="/cuentos-para-dormir">Cuentos para dormir </a>--}}
                                {{--<a class="dropdown-item" href="/fabulas-para-niños">Fábulas cortas</a>--}}
                                {{--<a class="dropdown-item" href="/mitos-y-leyendas-para-niños">Mitos y leyendas</a>--}}
                                {{--<a class="dropdown-item" href="/cuentos-en-ingles">Cuentos en inglés</a>--}}
                                {{--<a class="dropdown-item" href="/cuentos-inventados">Cuentos inventados</a>--}}
                                {{--<a class="dropdown-item" href="/poemas-para-niños">Poemas para niños</a>--}}
                                {{--<a class="dropdown-item" href="/cuentos-hermanos-grimm">Cuentos hermanos Grimm</a>--}}
                                {{--<a class="dropdown-item" href="/cuentos-del-mundo">Cuentos del mundo</a>--}}
                            {{--</div>--}}
                        {{--</li>--}}
                        {{--<li class="nav-item2 dropdown py-0">--}}
                            {{--<a class="nav-link active dropdown-toggle py-0" data-toggle="dropdown" href="#">--}}
                                {{--Abecedario <span class="sr-only">(current)</span>--}}
                            {{--</a>--}}
                            {{--<div class="dropdown-menu" data-toggle="collapse" data-target=".navbar-collapse.show">--}}
                                {{--<a class="dropdown-item" href="/juegos-de-vocales">Juegos de vocales</a>--}}
                                {{--<a class="dropdown-item" href="/juegos-del-abecedario">Juegos del abecedario </a>--}}
                            {{--</div>--}}
                        {{--</li>--}}
                        {{--<li class="nav-item2 dropdown py-0">--}}
                            {{--<a class="nav-link active dropdown-toggle py-0" data-toggle="dropdown" href="#">--}}
                                {{--Matemática <span class="sr-only">(current)</span>--}}
                            {{--</a>--}}
                            {{--<div class="dropdown-menu" data-toggle="collapse" data-target=".navbar-collapse.show">--}}
                                {{--<a class="dropdown-item" href="/juegos-de-matematicas">Juegos de matemáticas</a>--}}
                                {{--<a class="dropdown-item" href="/juegos-de-numeros">Juegos de números </a>--}}
                                {{--<a class="dropdown-item" href="/juegos-de-figuras-geometricas">Juegos de figuras geométricas</a>--}}
                                {{--<a class="dropdown-item" href="/juegos-de-sumas">Juegos de sumas </a>--}}
                                {{--<a class="dropdown-item" href="/juegos-de-restas">Juegos de restas</a>--}}
                            {{--</div>--}}
                        {{--</li>--}}
                        {{--<li class="nav-item2 dropdown py-0">--}}
                            {{--<a class="nav-link active dropdown-toggle py-0" data-toggle="dropdown" href="#">--}}
                                {{--Inglés <span class="sr-only">(current)</span>--}}
                            {{--</a>--}}
                            {{--<div class="dropdown-menu" data-toggle="collapse" data-target=".navbar-collapse.show">--}}
                                {{--<a class="dropdown-item" href="/juegos-de-ingles">Juegos de inglés </a>--}}
                                {{--<a class="dropdown-item" href="/colores-en-ingles">Los colores en inglés </a>--}}
                                {{--<a class="dropdown-item" href="/numeros-en-ingles">Los números en inglés </a>--}}
                                {{--<a class="dropdown-item" href="/abecedario-en-ingles">El abecedario en inglés</a>--}}
                                {{--<a class="dropdown-item" href="/vocabulario-en-ingles">Vocabulario en inglés</a>--}}
                                {{--<a class="dropdown-item" href="/adivinanzas-en-ingles">Adivinanzas en inglés</a>--}}
                                {{--<a class="dropdown-item" href="/trabalenguas-en-ingles">Trabalenguas en inglés</a>--}}
                            {{--</div>--}}
                        {{--</li>--}}
                        {{--<li class="nav-item2 dropdown py-0">--}}
                            {{--<a class="nav-link active dropdown-toggle py-0" data-toggle="dropdown" href="#">--}}
                                {{--Ciencia <span class="sr-only">(current)</span>--}}
                            {{--</a>--}}
                            {{--<div class="dropdown-menu" data-toggle="collapse" data-target=".navbar-collapse.show">--}}
                                {{--<a class="dropdown-item" href="/ciencia-para-niños">Ciencia para niños </a>--}}
                                {{--<a class="dropdown-item" href="/experimentos-caseros-para-niños">Experimentos caseros </a>--}}
                                {{--<a class="dropdown-item" href="/ciencias-tecnologia">Ciencia y tecnología </a>--}}
                                {{--<a class="dropdown-item" href="/imagenes-de-animales">Animales para niños </a>--}}
                            {{--</div>--}}
                        {{--</li>--}}
                        @guest
                            <li class="nav-item2 py-0" data-toggle="collapse" data-target=".navbar-collapse.show">
                                @if (Route::has('login'))
                                    <a class="nav-link active py-0" href="{{ route('login') }}">Iniciar yojhaira</a> <!--- ACA ES EL INICIAR SESION --->
                               <!--- @endif
                            </li>
                            <li class="nav-item2 py-0" data-toggle="collapse" data-target=".navbar-collapse.show">
                                @if (Route::has('login'))
                                    <a class="nav-link active py-0" href="{{ route('register') }}">Registrar</a>
                                     @endif --->
                            </li>
                        @else
                            <li class="nav-item2 dropdown py-0">
                                <a class="nav-link active dropdown-toggle py-0" data-toggle="dropdown" href="#">
                                    {{ Auth::user()->name }}<span class="sr-only">(current)</span>
                                </a>
                                <div class="dropdown-menu" data-toggle="collapse" data-target=".navbar-collapse.show" style="left: -4em;">
                                    @if(Auth::user()->is_admin)
                                        <a class="dropdown-item" href="{{ url('admin/categories') }}">Categorías</a>
                                        <a class="dropdown-item" href="{{ url('admin/pictures') }}">Dibujos</a>
                                        <a class="dropdown-item" href="{{ route('register') }}">Registrar</a> 
                                    @endif
                                    @if(Auth::user()->is_teacher)
                                        <a class="dropdown-item" href="{{ url('teacher/students') }}">Alumnos </a>
                                    @endif
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                        Cerrar sesión
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/home">Inicio <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/home#section2">Nosotros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/home#section3">Actividades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/home#contactanos">Contáctanos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {{--<nav class="navbar navbar-expand nav-bottom navbar-dark">--}}
            {{--<ul class="navbar-nav nav-row py-0 mr-auto ml-auto" id="nav-top">--}}
                {{--<li class="nav-item dropdown py-0" id="nuestra-portal">--}}
                    {{--<a class="nav-link active dropdown-toggle py-0 nav-test" data-toggle="dropdown" href="/juegos-para-ninos-de-preescolar">--}}
                        {{--Nuestro Portal <span class="sr-only">(current)</span>--}}
                    {{--</a>--}}
                    {{--<div class="dropdown-menu">--}}
                        {{--<a class="dropdown-item" href="/nuestra-historia">Nuestra Historia</a>--}}
                        {{--<a class="dropdown-item" href="/metodologia">Metodología</a>--}}
                        {{--<a class="dropdown-item" href="/curriculo">Currículo</a>--}}
                        {{--<a class="dropdown-item" href="/mision-social">Misión Social</a>--}}
                        {{--<a class="dropdown-item" href="/frases-de-educacion">Frases Educativas</a>--}}
                    {{--</div>--}}
                {{--</li>--}}
                {{--<li class="nav-item py-0">--}}
                    {{--<a class="nav-link active py-0" href="/juegos-para-ninos-de-preescolar">Niños 3 a 5</a>--}}
                {{--</li>--}}
                {{--<li class="nav-item py-0">--}}
                    {{--<a class="nav-link active py-0" href="/juegos-para-ninos-6-y-7-anos">Niños 5 a 7</a>--}}
                {{--</li><li class="nav-item py-0">--}}
                    {{--<a class="nav-link active py-0" href="/lecturas-cortas-para-niños">Niños 7 a 10</a>--}}
                {{--</li>--}}
            {{--</ul>--}}
        {{--</nav>--}}
</header>

@section('scripts')
<script>
    $(window).on("scroll", function() {
        if($(window).scrollTop() > 50) {
            $("#main-header").addClass("activeHeader");
            console.log("aaaaaa");
            
        } else {
            //remove the background property so it comes transparent again (defined in your css)
        $("#main-header").removeClass("activeHeader");
        }
    });
</script>
@endsection